### ISSUE TITLE
Rounding for currencies with no decimals (e.g. JPY) broken

### ISSUE THREAD

**Issue by racitup** [panosl/django-currencies#57]
On review of [utils.py](https://github.com/panosl/django-currencies/blob/master/currencies/utils.py) it appears that the `price_rounding` function requires decimals >=2. Currencies such as JPY don't have a decimal (==0).

**Comment by einarf** [comment]
I added the possibility to use more than 2 decimals and set the previous hardcoded default (2) as a limitation because I was not comfortable with changing the old behaviour without adding unit test with a specific a specific example.

Would this mean that currencies should also store their default rounding?

**Comment by racitup** [comment]
Very sensible!
If you look at my [django-shop branch](https://github.com/racitup/django-currencies/tree/shop_moneymaker), the money types automatically use the exponent from the currency iso source stored in the info column.. so in a way they are already stored!

**Comment by panosl** [comment]
Merged and fixed.
